config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }, path_names: {sign_in: "login", sign_out: "logout"}

  get "train", to: "trainer#index"

  get "browse", to: "browse#index"

  patch "train/score/:card_id", to: "trainer#score"

  scope ":username", :as => "user" do
    get 'cards', to: 'manager#index'
  end

  namespace :api do
    namespace :v1 do
      resources :cards
      resources :tags
      get 'card/blank', to: 'cards#blank'
      post 'cards/import', to: 'cards#import'
    end
  end

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<div id="home">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3>Welcome <%= current_user.first_name %></h3>
      <h5>Let's get to work.</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= link_to "Train", train_path, class: "btn btn-primary btn-main-nav btn-lg btn-block" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= link_to "Manage", user_cards_path(username: current_user.username), class: "btn btn-primary btn-main-nav btn-lg btn-block" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= link_to "Browse", browse_path, class: "btn btn-primary btn-main-nav btn-lg btn-block" %>
    </div>
  </div>
</div>